version: "3.2"
services:
  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Passwd1!
      - ACCEPT_EULA=Y
    volumes:
      - "data:/var/opt/mssql/data"

volumes:
  data:
